default_language_version:
  python: python3
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-case-conflict
      - id: check-yaml
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        args:
          - -l 128
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.0.1'
    hooks:
      - id: mypy
        args:
          - --ignore-missing-imports
        additional_dependencies:
          - types-pyyaml
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        files: ^qblagues/.*\.py$
        additional_dependencies: ["flake8-qgis<2"]
        args:
          [
            "--config=setup.cfg",
            "--select=E9,F63,F7,F82,QGS101,QGS102,QGS103,QGS104,QGS106",
          ]
