bots:

    # Favourite Bot Being
    favourite:
        # Mastodon API connection settings
        api:
            api_base_url: https://mastodon.instance/
            access_token: secret_access_token
        # if the bot should interact with humans and related toots (default: false)
        interact_with_humans: false
        # if the bot should interact with bots and related toots (default: true)
        interact_with_bots: true
        # how many toots should be asked to mastodon API when fetching timeline (default: 20)
        fetch_timeline_limit: 20

    # Boost Bot Being
    boost:
        # Mastodon API connection settings
        api:
            api_base_url: https://mastodon.instance/
            access_token: secret_access_token
        # if the bot should interact with humans and related toots (default: false)
        interact_with_humans: false
        # if the bot should interact with bots and related toots (default: true)
        interact_with_bots: true
        # how many toots should be asked to mastodon API when fetching timeline (default: 20)
        fetch_timeline_limit: 20

    # Follow Bot Being
    follow:
        # Mastodon API connection settings
        api:
            api_base_url: https://mastodon.instance/
            access_token: secret_access_token
        # if the bot should interact with humans and related toots (default: false)
        interact_with_humans: true
        # if the bot should interact with bots and related toots (default: true)
        interact_with_bots: true
        # how many toots should be asked to mastodon API when fetching timeline (default: 20)
        fetch_timeline_limit: 20
        fetch_followers_limit: 20

    # Quote Bot Being
    quote:
        # Mastodon API connection settings
        api:
            api_base_url: https://mastodon.instance/
            access_token: secret_access_token

    # Toni Mastodoni
    tonimastodoni:
        # Mastodon API connection settings
        api:
            api_base_url: https://mastodon.instance/
            access_token: secret_access_token
        # how many toots should be asked to mastodon API when fetching timeline (default: 20)
        fetch_timeline_limit: 20
